### ISSUE TITLE
[RfC] disconnect on DESTROY

### ISSUE THREAD

**Issue by abraxxa** [net-amqp-rabbitmq/net-amqp-rabbitmq#148]
I think this is useful as downstream modules don't need to care about that in their DESTROY method then.

**Comment by mjegh** [comment]
I believe it does this now. See issue 152 where it causes a problem.

**Comment by abraxxa** [comment]
Issue #151?

**Comment by mjegh** [comment]
Sorry, yes, issue 151.

**Comment by abraxxa** [comment]
Please implement this as it causes Perl to hang in DESTROY from time to time:

```
(gdb) bt
#0  0x00007f8f4f115ad0 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f8f4a9fa4fb in amqp_poll () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#2  0x00007f8f4a9fa60f in recv_with_timeout () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#3  0x00007f8f4a9faced in wait_frame_inner () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#4  0x00007f8f4a9fb327 in amqp_simple_rpc () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#5  0x00007f8f4a9f3233 in amqp_connection_close () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#6  0x00007f8f4a9eacff in XS_Net__AMQP__RabbitMQ_DESTROY () from /home/nac/perl5/perlbrew/perls/COLLECTOR/lib/site_perl/5.22.1/x86_64-linux/auto/Net/AMQP/RabbitMQ/RabbitMQ.so
#7  0x00000000004b1df7 in Perl_pp_entersub ()
#8  0x000000000043cc87 in Perl_call_sv ()
#9  0x00000000004b6657 in S_curse ()
#10 0x00000000004b6e85 in Perl_sv_clear ()
#11 0x00000000004b71b2 in Perl_sv_free2 ()
#12 0x00000000004b53c2 in S_visit ()
#13 0x00000000004b753c in Perl_sv_clean_objs ()
#14 0x000000000043f06b in perl_destruct ()
#15 0x00000000004207b4 in main ()
```

**Comment by abraxxa** [comment]
Can this cause the issue?

https://metacpan.org/source/ABRAXXA/Log-Log4perl-Appender-RabbitMQ-0.200001/lib/Log/Log4perl/Appender/RabbitMQ.pm#L167

**Comment by markwellis** [comment]
I think this is fixed now with the connection keep alive thing #164
